### ISSUE TITLE
[games-strategy/freeciv] missing dependency

### ISSUE THREAD

**Issue by velnias75** [hasufell/games-overlay#23]
Dependency to `media-libs/sdl-ttf` is missing...

**Comment by hasufell** [comment]
do you happen to have qt5 enabled? I couldn't test it, so I just assumed it works

**Comment by velnias75** [comment]
I haven't qt5 enabled. My USE flags: aimodules, auth, gtk, ipv6, mapimg, 
modpack, mysql, nls, readline, **sdl**, server, sound, sqlite
