### ISSUE TITLE
NetMauMau version 0.7 and 0.8

### ISSUE THREAD

**Issue by velnias75** [hasufell/games-overlay#4]
Please feel free to have a look at at this [diff](https://gist.github.com/velnias75/107d45e90b08abe57bcf) :grinning:

**Comment by hasufell** [comment]
The diff just shows me the whole ebuilds, not the diff to the older versions.

**Comment by velnias75** [comment]
Ok, forget it. I'm tired about doing more work on this goddamn ebuilds than on NetMauMau itself...

**Comment by hasufell** [comment]
You can just tell me what changed, e.g.
* new deps? removed deps?
* new useful build-time switches for the user? something removed?
* ...

**Comment by hasufell** [comment]
You should fork this repo and try again. It's the perfect advantage to learn git. But I cannot help or provide working git commands if you delete the repository...

**Comment by velnias75** [comment]
Ok, but I don't want to spend more time on git and ebuilds than on developing.

It would be the best, you could just write me down once the git commands for 
following workflow:


If I start a new release I copy the old ebuild file and rename it to the new 
version.
Every now and then I touch this file to add my changes. The Manifest gets 
changed permanently by ebuild.
Whenever my fork lags behind yours, I want to sync it.

After a release I test it on Gentoo directly from the Git tag, do final 
touches and than I want to make a pull request, which will not end up in 
lengthy discussion about **GIT**. About the ebuilds we can discuss as much as 
we want and needed.

**Comment by hasufell** [comment]
> Whenever my fork lags behind yours, I want to sync it.

To sync, you do:
```
git remote add upstream git@github.com:hasufell/games-overlay.git # only once
git pull upstream master
```

Fix conflicts if any. Done. Ofc you could do rebases instead of merges if you know how, but that's a bit more advanced (but helps with maintaining a cleaner history).

**Comment by velnias75** [comment]
I forked it again, but I'n not on my Gentoo-VM right now. Will do the rest later.
Ok, I know how to sync. But how can I produce pull requests that will satisfy you?
Forgot to mention, that if I use a VCS, I would like to commit my changes in my fork. Will you complain about too many commits in the pull request?

**Comment by hasufell** [comment]
> Will you complain about too many commits in the pull request?

If there are like 10 commits that do the same thing, you can squash them:
```
git rebase -i HEAD~10
# editor opens... replase 'pick' with 'fixup' or 'squash' on those commits
# you want to squash into the previous one
# save editor and exit it
```

**Comment by velnias75** [comment]
So, I prepared the new fork. But now there is the ebuild for upcoming 0.9 
included. How to keep it and exclude it in the pull request?

**Comment by hasufell** [comment]
> So, I prepared the new fork. But now there is the ebuild for upcoming 0.9 included. How to keep it and exclude it in the pull request?

I think you can specify that in the pull request (somewhere in the github UI)... otherwise I can handle that myself and only pull up to that commit.

Alternatively you can create a dedicated branch up to the commit you want to be pulled:
```
git checkout -b PR-NetMauMau <commit-hash before 0.9 got included>
```

**Comment by velnias75** [comment]
ok, this time you need to care of the Manifest and the 0.9 version. I prepare a pull req now

**Comment by velnias75** [comment]
Since there is more you can do **wrong** than *right*, how can I do now this two things:

* sync the repo
* making a pull request out of the current that need not to be discussed for days?
