### ISSUE TITLE
games-action/freeminer

### ISSUE THREAD

**Issue by netfab** [hasufell/games-overlay#44]
Hi,

Since you have games-action/minetest{_game}, could someone please have a look at freeminer ?
Unlike minetest, this fork seems to have NLS support.

http://freeminer.org/
https://github.com/freeminer/freeminer
https://bugs.funtoo.org/browse/FL-2870

Thanks !

**Comment by hasufell** [comment]
open a PR

**Comment by netfab** [comment]
Forget it. I thought it was fully translatable, but it is not. It seems only to have UTF-8 support.

Like minetest, the main engine is localizable, but after looking to games/default submodule, I realized that mods are not, and this makes the main game unplayable for anyone that does not understand english. A fork like an other. Closing this.
