### ISSUE TITLE
Request required USE flags from openscenegraph

### ISSUE THREAD

**Issue by TheReverend403** [hasufell/games-overlay#46]
According to https://wiki.openmw.org/index.php?title=Development_Environment_Setup#Gentoo openmw needs more USE flags for openscenegraph than this overlay asks for, leading to confusion when ERROR: Failed to create SDL window: No OpenGL support in video driver happens because openscenegraph has no SDL support.

**Comment by hasufell** [comment]
Where does that error occur? I can start morrowind fine without those USE flags.

**Comment by TheReverend403** [comment]
Interesting. I'll look further into this.

**Comment by TheReverend403** [comment]
Ah, silly me. I was setting the right use flags for libsdl, not libsdl2 like openmw requires. Sorry for wasting your time. :)

**Comment by hasufell** [comment]
:rage1:
