### ISSUE TITLE
games-engines/odamex/files/odamex-0.7.0-miniupnpc.patch does not apply

### ISSUE THREAD

**Issue by Mailaender** [hasufell/games-overlay#50]
I tried patch levels 0, 1 and 2. All hunks always fail.

**Comment by hasufell** [comment]
From within the `src-7.0` directory inside the tarball the correct patch-level is `-p1`. Note that the files have special dos line endings, which might not be preserved if you copy-paste it. So either preserve the patch as-is or use `dos2unix` on the source files before patching.
