### ISSUE TITLE
[games-strategy/wesnoth] error: no matching function for call to 'boost::none_t::none_t()'

### ISSUE THREAD

**Issue by Dr-Terrible** [hasufell/games-overlay#55]
`games-strategy/wesnoth-1.13.2` doesn't compile anymore with `dev-libs/boost` v1.60.0+ (which is the stable version in Portage):

```shell
[  2%] Building CXX object src/CMakeFiles/wesnoth-core.dir/log.cpp.o
In file included from /var/tmp/portage/games-strategy/wesnoth-1.13.2/work/wesnoth-1.13.2/src/display.cpp:34:0:
/var/tmp/portage/games-strategy/wesnoth-1.13.2/work/wesnoth-1.13.2/src/play_controller.hpp: In member function 'void play_controller::reset_end_level_data()':
/var/tmp/portage/games-strategy/wesnoth-1.13.2/work/wesnoth-1.13.2/src/play_controller.hpp:140:47: error: no matching function for call to 'boost::none_t::none_t()'
   gamestate().end_level_data_ = boost::none_t();
                                               ^
In file included from /usr/include/boost/none.hpp:16:0,
                 from /usr/include/boost/optional/optional.hpp:47,
                 from /usr/include/boost/optional.hpp:15,
                 from /var/tmp/portage/games-strategy/wesnoth-1.13.2/work/wesnoth-1.13.2/src/game_end_exceptions.hpp:32,
                 from /var/tmp/portage/games-strategy/wesnoth-1.13.2/work/wesnoth-1.13.2/src/play_controller.hpp:21,
                 from /var/tmp/portage/games-strategy/wesnoth-1.13.2/work/wesnoth-1.13.2/src/display.cpp:34:
/usr/include/boost/none_t.hpp:32:12: note: candidate: boost::none_t::none_t(boost::none_t::init_tag)
   explicit none_t(init_tag){} // to disable default constructor
            ^
/usr/include/boost/none_t.hpp:32:12: note:   candidate expects 1 argument, 0 provided
/usr/include/boost/none_t.hpp:29:8: note: candidate: boost::none_t::none_t(const boost::none_t&)
 struct none_t
        ^
/usr/include/boost/none_t.hpp:29:8: note:   candidate expects 1 argument, 0 provided
make[2]: *** [src/CMakeFiles/wesnoth-game.dir/build.make:162: src/CMakeFiles/wesnoth-game.dir/display.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:291: src/CMakeFiles/wesnoth-game.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

The compilation error is related to the change in boost::none in [1.60.0](http://www.boost.org/users/history/version_1_60_0.html)

**Comment by Dr-Terrible** [comment]
The compilation error can be fixed by applying this patch: https://github.com/wesnoth/wesnoth/commit/aa1ea043bbf52d509197eab91ab85c70e633d69e.patch

See [upstream #24227](http://gna.org/bugs/?24227) for reference.

**Comment by Dr-Terrible** [comment]
Unless there are objections, I'll submit a PR that fixes #55, #54, and bump wesnoth to v1.13.6.

**Comment by hasufell** [comment]
The truth is... I don't actively develop gentoo anymore. I use it for a docker host and a chroot here and there, but not for my desktop/work activity. I can give you push access to this repo if you want to maintain it.

**Comment by Dr-Terrible** [comment]
>  I can give you push access to this repo if you want to maintain it.

Sure, I'll be glade to help; thank you for the offer, @hasufell.

I have also an handful of games in my overlay that I can move in this repo. While I'm at it, I can trim the old ebuilds, update the remaining ones, and improve the overlay to make it repoman's compliant. It's not a big deal ;)

**Comment by Corax** [comment]
Welp. I'm certain I copy/renamed the edited file, but whatever. I hope it's fine now.
