### ISSUE TITLE
games-fps/doomsday-1.14.5: confutils.eclass issues.

### ISSUE THREAD

**Issue by hanetzer** [hasufell/games-overlay#75]
1. `confutils.eclass` was killed off 2017-06-30 in gentoo/gentoo@992fa0e97367eac8a93db3f7c939285b49175d62
2. this ebuild actually makes no use of any of the old confutils functions
3. even with confutils removed from the inherit line, it cannot compile due to narrowing.
4. qt4 was eol'd at 2015-12

As such, with there being newer versions of doomsday in active development, this version
should be removed from the overlay.

**Comment by hasufell** [comment]
fix it

**Comment by hanetzer** [comment]
Doesn't need a fix, needs a kill.

**Comment by hanetzer** [comment]
https://bugs.gentoo.org/631788

**Comment by hasufell** [comment]
> Doesn't need a fix, needs a kill.

yes, *fix* it (by killing)
